/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    OneDriveTokenGenerator: typeof import('./src/components/OneDriveTokenGenerator.vue')['default']
    SessionGenerator: typeof import('./src/components/SessionGenerator.vue')['default']
  }
}
